id: I31BAF7C4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T23:03:25+00:00'
last_modified: '2022-06-09T06:41:43.991523+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD506
  title: ཐུབ་ཆོག་བྱིན་རླབས་གཏེར་མཛོད་ཀྱི་རྒྱབ་ཆོས་པདྨ་དཀར་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    6C7C:
      image_group_id: I4PD554
      title: Volume 1 of thub chog byin rlabs gter mdzod kyi rgyab chos pad+ma dkar
        po/
      total_pages: 1012
      order: 1
      base_file: 6C7C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
