id: P007859
initial_creation_type: ocr
source_metadata:
  id: bdr:W4PD506
  title: ཐུབ་ཆོག་བྱིན་རླབས་གཏེར་མཛོད་ཀྱི་རྒྱབ་ཆོས་པདྨ་དཀར་པོ།
  author: ''
  volumes:
    85f6a6576ebe45bab931c3da2d510405:
      image_group_id: I4PD554
      title: ''
      volume_number: 1
      total_pages: 1012
ebook_metadata:
  title: ཐུབ་ཆོག་བྱིན་རླབས་གཏེར་མཛོད་ཀྱི་རྒྱབ་ཆོས་པདྨ་དཀར་པོ།
  author: ''
  sku: P007859
  cover: cover.jpg
  layers:
  - pagination
