id: P007859
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W4PD506
  title: ཐུབ་ཆོག་བྱིན་རླབས་གཏེར་མཛོད་ཀྱི་རྒྱབ་ཆོས་པདྨ་དཀར་པོ།
  author: ''
  volumes:
    7a8ebbb5236640b2a0867a3860664547:
      image_group_id: I4PD554
      title: Volume 1 of thub chog byin rlabs gter mdzod kyi rgyab chos pad+ma dkar
        po/
      volume_number: 1
      total_pages: 1012
      base_file: v001.txt
